apiVersion: v1
kind: Service
metadata:
  annotations:
    apiRoute: /api/v1/users
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "3070"
    port: 3070
    targetPort: 3000
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  loadBalancer: {}

