apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    apiRoute: /api/v1/users
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        apiRoute: /api/v1/users
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: APP_SETTINGS
          value: production
        - name: DATABASE_URL
          value: postgres://postgres:postgres@db/auth_db
        - name: NODE_ENV
          value: docker
        - name: REDIS_URL
          value: redis://cache
        # image: gcr.io/summer-hawk-258307/web
        image: wagubib/microservice:auth
        name: auth-service
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
